// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Compliant     bool                   `protobuf:"varint,3,opt,name=compliant,proto3" json:"compliant,omitempty"`
	ResolvedIp    string                 `protobuf:"bytes,4,opt,name=resolved_ip,json=resolvedIp,proto3" json:"resolved_ip,omitempty"`
	Screenshot    []byte                 `protobuf:"bytes,5,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	DnsServer     string                 `protobuf:"bytes,7,opt,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ResolvedIpv6  string                 `protobuf:"bytes,9,opt,name=resolved_ipv6,json=resolvedIpv6,proto3" json:"resolved_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteResult) Reset() {
	*x = SiteResult{}
	mi := &file_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteResult) ProtoMessage() {}

func (x *SiteResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteResult.ProtoReflect.Descriptor instead.
func (*SiteResult) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *SiteResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SiteResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SiteResult) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

func (x *SiteResult) GetResolvedIp() string {
	if x != nil {
		return x.ResolvedIp
	}
	return ""
}

func (x *SiteResult) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *SiteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SiteResult) GetDnsServer() string {
	if x != nil {
		return x.DnsServer
	}
	return ""
}

func (x *SiteResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SiteResult) GetResolvedIpv6() string {
	if x != nil {
		return x.ResolvedIpv6
	}
	return ""
}

type ComplianceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SiteResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceReport) Reset() {
	*x = ComplianceReport{}
	mi := &file_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceReport) ProtoMessage() {}

func (x *ComplianceReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceReport.ProtoReflect.Descriptor instead.
func (*ComplianceReport) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *ComplianceReport) GetResults() []*SiteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *Acknowledgement) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DNSServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Isp           string                 `protobuf:"bytes,1,opt,name=isp,proto3" json:"isp,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSServerConfig) Reset() {
	*x = DNSServerConfig{}
	mi := &file_proto_compliance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSServerConfig) ProtoMessage() {}

func (x *DNSServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSServerConfig.ProtoReflect.Descriptor instead.
func (*DNSServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *DNSServerConfig) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}

func (x *DNSServerConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSServerConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DNSServerConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type SweepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	DnsServers    []*DNSServerConfig     `protobuf:"bytes,2,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	CompliantIps  []string               `protobuf:"bytes,3,rep,name=compliant_ips,json=compliantIps,proto3" json:"compliant_ips,omitempty"`
	Screenshots   bool                   `protobuf:"varint,4,opt,name=screenshots,proto3" json:"screenshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SweepRequest) Reset() {
	*x = SweepRequest{}
	mi := &file_proto_compliance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SweepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SweepRequest) ProtoMessage() {}

func (x *SweepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SweepRequest.ProtoReflect.Descriptor instead.
func (*SweepRequest) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{4}
}

func (x *SweepRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *SweepRequest) GetDnsServers() []*DNSServerConfig {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *SweepRequest) GetCompliantIps() []string {
	if x != nil {
		return x.CompliantIps
	}
	return nil
}

func (x *SweepRequest) GetScreenshots() bool {
	if x != nil {
		return x.Screenshots
	}
	return false
}

type SweepAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SweepAck) Reset() {
	*x = SweepAck{}
	mi := &file_proto_compliance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SweepAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SweepAck) ProtoMessage() {}

func (x *SweepAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SweepAck.ProtoReflect.Descriptor instead.
func (*SweepAck) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *SweepAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SweepAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_compliance_proto protoreflect.FileDescriptor

const file_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/compliance.proto\x12\n" +
	"compliance\"\x94\x02\n" +
	"\n" +
	"SiteResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tcompliant\x18\x03 \x01(\bR\tcompliant\x12\x1f\n" +
	"\vresolved_ip\x18\x04 \x01(\tR\n" +
	"resolvedIp\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x05 \x01(\fR\n" +
	"screenshot\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"dns_server\x18\a \x01(\tR\tdnsServer\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x03R\tlatencyMs\x12#\n" +
	"\rresolved_ipv6\x18\t \x01(\tR\fresolvedIpv6\"D\n" +
	"\x10ComplianceReport\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.compliance.SiteResultR\aresults\"!\n" +
	"\x0fAcknowledgement\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"m\n" +
	"\x0fDNSServerConfig\x12\x10\n" +
	"\x03isp\x18\x01 \x01(\tR\x03isp\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"\xa7\x01\n" +
	"\fSweepRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12<\n" +
	"\vdns_servers\x18\x02 \x03(\v2\x1b.compliance.DNSServerConfigR\n" +
	"dnsServers\x12#\n" +
	"\rcompliant_ips\x18\x03 \x03(\tR\fcompliantIps\x12 \n" +
	"\vscreenshots\x18\x04 \x01(\bR\vscreenshots\"<\n" +
	"\bSweepAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2X\n" +
	"\x11ComplianceService\x12C\n" +
	"\x06Submit\x12\x1c.compliance.ComplianceReport\x1a\x1b.compliance.Acknowledgement2N\n" +
	"\x0eCrawlerControl\x12<\n" +
	"\n" +
	"StartSweep\x12\x18.compliance.SweepRequest\x1a\x14.compliance.SweepAckB$Z\"github.com/afif/dns-tracking/protob\x06proto3"

var (
	file_proto_compliance_proto_rawDescOnce sync.Once
	file_proto_compliance_proto_rawDescData []byte
)

func file_proto_compliance_proto_rawDescGZIP() []byte {
	file_proto_compliance_proto_rawDescOnce.Do(func() {
		file_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)))
	})
	return file_proto_compliance_proto_rawDescData
}

var file_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_compliance_proto_goTypes = []any{
	(*SiteResult)(nil),       // 0: compliance.SiteResult
	(*ComplianceReport)(nil), // 1: compliance.ComplianceReport
	(*Acknowledgement)(nil),  // 2: compliance.Acknowledgement
	(*DNSServerConfig)(nil),  // 3: compliance.DNSServerConfig
	(*SweepRequest)(nil),     // 4: compliance.SweepRequest
	(*SweepAck)(nil),         // 5: compliance.SweepAck
}
var file_proto_compliance_proto_depIdxs = []int32{
	0, // 0: compliance.ComplianceReport.results:type_name -> compliance.SiteResult
	3, // 1: compliance.SweepRequest.dns_servers:type_name -> compliance.DNSServerConfig
	1, // 2: compliance.ComplianceService.Submit:input_type -> compliance.ComplianceReport
	4, // 3: compliance.CrawlerControl.StartSweep:input_type -> compliance.SweepRequest
	2, // 4: compliance.ComplianceService.Submit:output_type -> compliance.Acknowledgement
	5, // 5: compliance.CrawlerControl.StartSweep:output_type -> compliance.SweepAck
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_compliance_proto_init() }
func file_proto_compliance_proto_init() {
	if File_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_compliance_proto_goTypes,
		DependencyIndexes: file_proto_compliance_proto_depIdxs,
		MessageInfos:      file_proto_compliance_proto_msgTypes,
	}.Build()
	File_proto_compliance_proto = out.File
	file_proto_compliance_proto_goTypes = nil
	file_proto_compliance_proto_depIdxs = nil
}
