// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SiteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Compliant     bool                   `protobuf:"varint,3,opt,name=compliant,proto3" json:"compliant,omitempty"`
	ResolvedIp    string                 `protobuf:"bytes,4,opt,name=resolved_ip,json=resolvedIp,proto3" json:"resolved_ip,omitempty"`
	Screenshot    []byte                 `protobuf:"bytes,5,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteResult) Reset() {
	*x = SiteResult{}
	mi := &file_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteResult) ProtoMessage() {}

func (x *SiteResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteResult.ProtoReflect.Descriptor instead.
func (*SiteResult) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *SiteResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SiteResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SiteResult) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

func (x *SiteResult) GetResolvedIp() string {
	if x != nil {
		return x.ResolvedIp
	}
	return ""
}

func (x *SiteResult) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *SiteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ComplianceReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SiteResult          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplianceReport) Reset() {
	*x = ComplianceReport{}
	mi := &file_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceReport) ProtoMessage() {}

func (x *ComplianceReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceReport.ProtoReflect.Descriptor instead.
func (*ComplianceReport) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *ComplianceReport) GetResults() []*SiteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *Acknowledgement) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_compliance_proto protoreflect.FileDescriptor

const file_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/compliance.proto\x12\n" +
	"compliance\"\xb1\x01\n" +
	"\n" +
	"SiteResult\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tcompliant\x18\x03 \x01(\bR\tcompliant\x12\x1f\n" +
	"\vresolved_ip\x18\x04 \x01(\tR\n" +
	"resolvedIp\x12\x1e\n" +
	"\n" +
	"screenshot\x18\x05 \x01(\fR\n" +
	"screenshot\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"D\n" +
	"\x10ComplianceReport\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.compliance.SiteResultR\aresults\"!\n" +
	"\x0fAcknowledgement\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2X\n" +
	"\x11ComplianceService\x12C\n" +
	"\x06Submit\x12\x1c.compliance.ComplianceReport\x1a\x1b.compliance.AcknowledgementB$Z\"github.com/afif/dns-tracking/protob\x06proto3"

var (
	file_proto_compliance_proto_rawDescOnce sync.Once
	file_proto_compliance_proto_rawDescData []byte
)

func file_proto_compliance_proto_rawDescGZIP() []byte {
	file_proto_compliance_proto_rawDescOnce.Do(func() {
		file_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)))
	})
	return file_proto_compliance_proto_rawDescData
}

var file_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_compliance_proto_goTypes = []any{
	(*SiteResult)(nil),       // 0: compliance.SiteResult
	(*ComplianceReport)(nil), // 1: compliance.ComplianceReport
	(*Acknowledgement)(nil),  // 2: compliance.Acknowledgement
}
var file_proto_compliance_proto_depIdxs = []int32{
	0, // 0: compliance.ComplianceReport.results:type_name -> compliance.SiteResult
	1, // 1: compliance.ComplianceService.Submit:input_type -> compliance.ComplianceReport
	2, // 2: compliance.ComplianceService.Submit:output_type -> compliance.Acknowledgement
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_compliance_proto_init() }
func file_proto_compliance_proto_init() {
	if File_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_compliance_proto_rawDesc), len(file_proto_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_compliance_proto_goTypes,
		DependencyIndexes: file_proto_compliance_proto_depIdxs,
		MessageInfos:      file_proto_compliance_proto_msgTypes,
	}.Build()
	File_proto_compliance_proto = out.File
	file_proto_compliance_proto_goTypes = nil
	file_proto_compliance_proto_depIdxs = nil
}
