// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/compliance.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ComplianceService_Submit_FullMethodName = "/compliance.ComplianceService/Submit"
)

// ComplianceServiceClient is the client API for ComplianceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComplianceServiceClient interface {
	Submit(ctx context.Context, in *ComplianceReport, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type complianceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComplianceServiceClient(cc grpc.ClientConnInterface) ComplianceServiceClient {
	return &complianceServiceClient{cc}
}

func (c *complianceServiceClient) Submit(ctx context.Context, in *ComplianceReport, opts ...grpc.CallOption) (*Acknowledgement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, ComplianceService_Submit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComplianceServiceServer is the server API for ComplianceService service.
// All implementations must embed UnimplementedComplianceServiceServer
// for forward compatibility.
type ComplianceServiceServer interface {
	Submit(context.Context, *ComplianceReport) (*Acknowledgement, error)
	mustEmbedUnimplementedComplianceServiceServer()
}

// UnimplementedComplianceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComplianceServiceServer struct{}

func (UnimplementedComplianceServiceServer) Submit(context.Context, *ComplianceReport) (*Acknowledgement, error) {
	return nil, status.Error(codes.Unimplemented, "method Submit not implemented")
}
func (UnimplementedComplianceServiceServer) mustEmbedUnimplementedComplianceServiceServer() {}
func (UnimplementedComplianceServiceServer) testEmbeddedByValue()                           {}

// UnsafeComplianceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComplianceServiceServer will
// result in compilation errors.
type UnsafeComplianceServiceServer interface {
	mustEmbedUnimplementedComplianceServiceServer()
}

func RegisterComplianceServiceServer(s grpc.ServiceRegistrar, srv ComplianceServiceServer) {
	// If the following call panics, it indicates UnimplementedComplianceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ComplianceService_ServiceDesc, srv)
}

func _ComplianceService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComplianceReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComplianceServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ComplianceService_Submit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComplianceServiceServer).Submit(ctx, req.(*ComplianceReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ComplianceService_ServiceDesc is the grpc.ServiceDesc for ComplianceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComplianceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compliance.ComplianceService",
	HandlerType: (*ComplianceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _ComplianceService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compliance.proto",
}

const (
	CrawlerControl_StartSweep_FullMethodName = "/compliance.CrawlerControl/StartSweep"
)

// CrawlerControlClient is the client API for CrawlerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CrawlerControlClient interface {
	StartSweep(ctx context.Context, in *SweepRequest, opts ...grpc.CallOption) (*SweepAck, error)
}

type crawlerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewCrawlerControlClient(cc grpc.ClientConnInterface) CrawlerControlClient {
	return &crawlerControlClient{cc}
}

func (c *crawlerControlClient) StartSweep(ctx context.Context, in *SweepRequest, opts ...grpc.CallOption) (*SweepAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SweepAck)
	err := c.cc.Invoke(ctx, CrawlerControl_StartSweep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CrawlerControlServer is the server API for CrawlerControl service.
// All implementations must embed UnimplementedCrawlerControlServer
// for forward compatibility.
type CrawlerControlServer interface {
	StartSweep(context.Context, *SweepRequest) (*SweepAck, error)
	mustEmbedUnimplementedCrawlerControlServer()
}

// UnimplementedCrawlerControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCrawlerControlServer struct{}

func (UnimplementedCrawlerControlServer) StartSweep(context.Context, *SweepRequest) (*SweepAck, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSweep not implemented")
}
func (UnimplementedCrawlerControlServer) mustEmbedUnimplementedCrawlerControlServer() {}
func (UnimplementedCrawlerControlServer) testEmbeddedByValue()                        {}

// UnsafeCrawlerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CrawlerControlServer will
// result in compilation errors.
type UnsafeCrawlerControlServer interface {
	mustEmbedUnimplementedCrawlerControlServer()
}

func RegisterCrawlerControlServer(s grpc.ServiceRegistrar, srv CrawlerControlServer) {
	// If the following call panics, it indicates UnimplementedCrawlerControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CrawlerControl_ServiceDesc, srv)
}

func _CrawlerControl_StartSweep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SweepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CrawlerControlServer).StartSweep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CrawlerControl_StartSweep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CrawlerControlServer).StartSweep(ctx, req.(*SweepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CrawlerControl_ServiceDesc is the grpc.ServiceDesc for CrawlerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CrawlerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "compliance.CrawlerControl",
	HandlerType: (*CrawlerControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSweep",
			Handler:    _CrawlerControl_StartSweep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/compliance.proto",
}
