/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlsRouteImport } from './routes/urls'
import { Route as ScanResultsRouteImport } from './routes/scan-results'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalCitationsRouteImport } from './routes/legal-citations'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DnsServersRouteImport } from './routes/dns-servers'
import { Route as BlockingStatsRouteImport } from './routes/blocking-stats'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as DomainIndexRouteImport } from './routes/domain.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as IspsIspRouteImport } from './routes/isps.$isp'
import { Route as DomainUrlRouteImport } from './routes/domain.$url'

const UrlsRoute = UrlsRouteImport.update({
  id: '/urls',
  path: '/urls',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan-results',
  path: '/scan-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCitationsRoute = LegalCitationsRouteImport.update({
  id: '/legal-citations',
  path: '/legal-citations',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsServersRoute = DnsServersRouteImport.update({
  id: '/dns-servers',
  path: '/dns-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockingStatsRoute = BlockingStatsRouteImport.update({
  id: '/blocking-stats',
  path: '/blocking-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultsRoute,
} as any)
const DomainIndexRoute = DomainIndexRouteImport.update({
  id: '/domain/',
  path: '/domain/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const IspsIspRoute = IspsIspRouteImport.update({
  id: '/isps/$isp',
  path: '/isps/$isp',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainUrlRoute = DomainUrlRouteImport.update({
  id: '/domain/$url',
  path: '/domain/$url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocking-stats': typeof BlockingStatsRoute
  '/dns-servers': typeof DnsServersRoute
  '/docs': typeof DocsRoute
  '/legal-citations': typeof LegalCitationsRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRouteWithChildren
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/domain/$url': typeof DomainUrlRoute
  '/isps/$isp': typeof IspsIspRoute
  '/admin/': typeof AdminIndexRoute
  '/domain/': typeof DomainIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocking-stats': typeof BlockingStatsRoute
  '/dns-servers': typeof DnsServersRoute
  '/docs': typeof DocsRoute
  '/legal-citations': typeof LegalCitationsRoute
  '/login': typeof LoginRoute
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/domain/$url': typeof DomainUrlRoute
  '/isps/$isp': typeof IspsIspRoute
  '/admin': typeof AdminIndexRoute
  '/domain': typeof DomainIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blocking-stats': typeof BlockingStatsRoute
  '/dns-servers': typeof DnsServersRoute
  '/docs': typeof DocsRoute
  '/legal-citations': typeof LegalCitationsRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRouteWithChildren
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/domain/$url': typeof DomainUrlRoute
  '/isps/$isp': typeof IspsIspRoute
  '/admin/': typeof AdminIndexRoute
  '/domain/': typeof DomainIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blocking-stats'
    | '/dns-servers'
    | '/docs'
    | '/legal-citations'
    | '/login'
    | '/results'
    | '/scan-results'
    | '/urls'
    | '/domain/$url'
    | '/isps/$isp'
    | '/admin/'
    | '/domain/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocking-stats'
    | '/dns-servers'
    | '/docs'
    | '/legal-citations'
    | '/login'
    | '/scan-results'
    | '/urls'
    | '/domain/$url'
    | '/isps/$isp'
    | '/admin'
    | '/domain'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blocking-stats'
    | '/dns-servers'
    | '/docs'
    | '/legal-citations'
    | '/login'
    | '/results'
    | '/scan-results'
    | '/urls'
    | '/domain/$url'
    | '/isps/$isp'
    | '/admin/'
    | '/domain/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlockingStatsRoute: typeof BlockingStatsRoute
  DnsServersRoute: typeof DnsServersRoute
  DocsRoute: typeof DocsRoute
  LegalCitationsRoute: typeof LegalCitationsRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  ScanResultsRoute: typeof ScanResultsRoute
  UrlsRoute: typeof UrlsRoute
  DomainUrlRoute: typeof DomainUrlRoute
  IspsIspRoute: typeof IspsIspRoute
  DomainIndexRoute: typeof DomainIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urls': {
      id: '/urls'
      path: '/urls'
      fullPath: '/urls'
      preLoaderRoute: typeof UrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-results': {
      id: '/scan-results'
      path: '/scan-results'
      fullPath: '/scan-results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-citations': {
      id: '/legal-citations'
      path: '/legal-citations'
      fullPath: '/legal-citations'
      preLoaderRoute: typeof LegalCitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-servers': {
      id: '/dns-servers'
      path: '/dns-servers'
      fullPath: '/dns-servers'
      preLoaderRoute: typeof DnsServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocking-stats': {
      id: '/blocking-stats'
      path: '/blocking-stats'
      fullPath: '/blocking-stats'
      preLoaderRoute: typeof BlockingStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/domain/': {
      id: '/domain/'
      path: '/domain'
      fullPath: '/domain/'
      preLoaderRoute: typeof DomainIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/isps/$isp': {
      id: '/isps/$isp'
      path: '/isps/$isp'
      fullPath: '/isps/$isp'
      preLoaderRoute: typeof IspsIspRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain/$url': {
      id: '/domain/$url'
      path: '/domain/$url'
      fullPath: '/domain/$url'
      preLoaderRoute: typeof DomainUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResultsRouteChildren {
  ResultsIndexRoute: typeof ResultsIndexRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsIndexRoute: ResultsIndexRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlockingStatsRoute: BlockingStatsRoute,
  DnsServersRoute: DnsServersRoute,
  DocsRoute: DocsRoute,
  LegalCitationsRoute: LegalCitationsRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRouteWithChildren,
  ScanResultsRoute: ScanResultsRoute,
  UrlsRoute: UrlsRoute,
  DomainUrlRoute: DomainUrlRoute,
  IspsIspRoute: IspsIspRoute,
  DomainIndexRoute: DomainIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
