/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlsRouteImport } from './routes/urls'
import { Route as ScanResultsRouteImport } from './routes/scan-results'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DnsServersRouteImport } from './routes/dns-servers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResultsUrlRouteImport } from './routes/results.$url'
import { Route as IspsIspRouteImport } from './routes/isps.$isp'

const UrlsRoute = UrlsRouteImport.update({
  id: '/urls',
  path: '/urls',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanResultsRoute = ScanResultsRouteImport.update({
  id: '/scan-results',
  path: '/scan-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsServersRoute = DnsServersRouteImport.update({
  id: '/dns-servers',
  path: '/dns-servers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResultsUrlRoute = ResultsUrlRouteImport.update({
  id: '/$url',
  path: '/$url',
  getParentRoute: () => ResultsRoute,
} as any)
const IspsIspRoute = IspsIspRouteImport.update({
  id: '/isps/$isp',
  path: '/isps/$isp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dns-servers': typeof DnsServersRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRouteWithChildren
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/isps/$isp': typeof IspsIspRoute
  '/results/$url': typeof ResultsUrlRoute
  '/admin/': typeof AdminIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dns-servers': typeof DnsServersRoute
  '/login': typeof LoginRoute
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/isps/$isp': typeof IspsIspRoute
  '/results/$url': typeof ResultsUrlRoute
  '/admin': typeof AdminIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dns-servers': typeof DnsServersRoute
  '/login': typeof LoginRoute
  '/results': typeof ResultsRouteWithChildren
  '/scan-results': typeof ScanResultsRoute
  '/urls': typeof UrlsRoute
  '/isps/$isp': typeof IspsIspRoute
  '/results/$url': typeof ResultsUrlRoute
  '/admin/': typeof AdminIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dns-servers'
    | '/login'
    | '/results'
    | '/scan-results'
    | '/urls'
    | '/isps/$isp'
    | '/results/$url'
    | '/admin/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dns-servers'
    | '/login'
    | '/scan-results'
    | '/urls'
    | '/isps/$isp'
    | '/results/$url'
    | '/admin'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dns-servers'
    | '/login'
    | '/results'
    | '/scan-results'
    | '/urls'
    | '/isps/$isp'
    | '/results/$url'
    | '/admin/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DnsServersRoute: typeof DnsServersRoute
  LoginRoute: typeof LoginRoute
  ResultsRoute: typeof ResultsRouteWithChildren
  ScanResultsRoute: typeof ScanResultsRoute
  UrlsRoute: typeof UrlsRoute
  IspsIspRoute: typeof IspsIspRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urls': {
      id: '/urls'
      path: '/urls'
      fullPath: '/urls'
      preLoaderRoute: typeof UrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-results': {
      id: '/scan-results'
      path: '/scan-results'
      fullPath: '/scan-results'
      preLoaderRoute: typeof ScanResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns-servers': {
      id: '/dns-servers'
      path: '/dns-servers'
      fullPath: '/dns-servers'
      preLoaderRoute: typeof DnsServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/results/$url': {
      id: '/results/$url'
      path: '/$url'
      fullPath: '/results/$url'
      preLoaderRoute: typeof ResultsUrlRouteImport
      parentRoute: typeof ResultsRoute
    }
    '/isps/$isp': {
      id: '/isps/$isp'
      path: '/isps/$isp'
      fullPath: '/isps/$isp'
      preLoaderRoute: typeof IspsIspRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ResultsRouteChildren {
  ResultsUrlRoute: typeof ResultsUrlRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

const ResultsRouteChildren: ResultsRouteChildren = {
  ResultsUrlRoute: ResultsUrlRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}

const ResultsRouteWithChildren =
  ResultsRoute._addFileChildren(ResultsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DnsServersRoute: DnsServersRoute,
  LoginRoute: LoginRoute,
  ResultsRoute: ResultsRouteWithChildren,
  ScanResultsRoute: ScanResultsRoute,
  UrlsRoute: UrlsRoute,
  IspsIspRoute: IspsIspRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
